config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'jobs' => 'welcome#jobs'

  post 'create_job' => 'welcome#create_job'
end

app/models/job_status.rb
class JobStatus

  REDIS_PREFIX = 'aj'
  STATUSES = [ENQUEUED = 1, STARTED = 2, FINISHED = 3]
  FINISHED_TTL = 5 # seconds

  attr_reader :job_class_name, :job_id, :status

  def initialize(key)
    @key = key
    _, @job_class_name, @job_id = @key.split(':')
    @status, @changed_at = redis.hgetall(@key).values_at('status', 'changed_at')
  end

  def enqueued?
    status.to_i == ENQUEUED
  end

  def started?
    status.to_i == STARTED
  end

  def finished?
    status.to_i == FINISHED
  end

  def destroy
    self.redis.del(key)
  end

  def self.set_job_status(job, status)
    raise ArgumentError, 'Invalid job status' unless STATUSES.include?(status)

    key = "#{REDIS_PREFIX}:#{job.class.name}:#{job.job_id}"
    redis.mapped_hmset(key, 'status' => status, 'changed_at' => Time.now.to_i)
    redis.expire(key, FINISHED_TTL) if status == FINISHED

    FayeHelper.push('/test', 'job_status_changed')
  end

  def self.all(job_class_name = '*')
    self.keys("#{job_class_name}:*").map { |key| self.new(key) }
  end

  def self.flush
    self.keys('*:*').map { |key| redis.del(key) }
  end

  def self.keys(pattern)
    redis.keys(REDIS_PREFIX + ':' + pattern)
  end

private

  def redis
    self.class.redis
  end

  def self.redis
    @redis ||= Redis.current
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index; end

  def jobs
    jobs = JobStatus.all
      .map { |job| job.as_json(except: ['key']) }
      .sort { |a, b| b['changed_at'] <=> a['changed_at'] }

    render json: {jobs: jobs}
  end

  def create_job
    SomeJob.perform_later

    render nothing: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faye_helper.rb
require 'net/http'

module FayeHelper
  HOST = "http://localhost:#{ENV['FAYE_PORT'] || 3000}"
  
  def self.url
    mountpoint = FayeRails::Middleware::DEFAULTS.fetch(:mount)
    HOST + mountpoint
  end

  def self.push(channel, data = nil, &block)
    message = {
      channel: channel,
      data: block_given? ? capture(&block) : data
    }

    Net::HTTP.post_form(URI.parse(url), message: message.to_json)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html ng-app="app"
  head
    title BackgroundJobs
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=PT+Sans:400,700'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  body
    == yield
    javascript: window.FAYE_URL = #{raw FayeHelper.url.to_json}
    = javascript_include_tag 'application'

app/views/welcome/index.html.slim
.container
  .row
    .col-sm-6.col-sm-offset-3
      h1.text-center JobStatus
      .text-center
        = link_to 'Create new job', create_job_path, remote: true, method: :post, class: 'btn btn-primary'
      br
      .panel.panel-default ng-controller="JobsController"
        .panel-body
          ul
            li ng-repeat="(k, item) in jobs"
              | {{item.job_class_name}} {{item.job_id}}
              div.pull-right class="label label-{{status_class[item.status]}}"
                | {{status_text[item.status]}}
            li ng-if="!jobs.length"
              .text-muted No jobs